apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: zaproxy-operator
    app.kubernetes.io/instance: webhook-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: zaproxy-operator
  name: zaproxy-operator-webhook-service
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 9443
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    control-plane: controller-manager
status:
  loadBalancer: {}
