# permissions for end users to edit zaproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: zaproxy-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: zaproxy-operator
    app.kubernetes.io/part-of: zaproxy-operator
    app.kubernetes.io/managed-by: kustomize
  name: zaproxy-editor-role
rules:
- apiGroups:
  - zaproxy.org
  resources:
  - zaproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - zaproxy.org
  resources:
  - zaproxies/status
  verbs:
  - get
