name: Sign Chart

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log into ghcr.io
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v2.2.3'

      - name: Sign image
        run: cosign sign --yes ghcr.io/digitalnostril/zaproxy-operator:0.0.63

      - name: Sign chart
        run: cosign sign --yes ghcr.io/digitalnostril/zaproxy-operator:0.1.0
