apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zaproxy-operator.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: zaproxy-operator
    app.kubernetes.io/part-of: zaproxy-operator
  {{- include "zaproxy-operator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}